#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'dbfit_test', :path => "vendor/cookbooks/dbfit_test"
cookbook 'postgresql', :git => "https://github.com/javornikolov/postgresql"
cookbook 'windows', :git => "https://github.com/opscode-cookbooks/windows.git",
  :ref => "6346c0da614fad2152bb34184e1f7e35ebf662c5"
cookbook 'git', :git => "https://github.com/javornikolov/git"

