#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'dbfit_test', :path => "vendor/cookbooks/dbfit_test"
cookbook 'postgresql', :git => "https://github.com/dbfit/postgresql"
cookbook 'git', :git => "https://github.com/dbfit/git"

