# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'vagrant_config_helper'

VAGRANTFILE_API_VERSION = "2"

file_to_disk = CONFIG['additional_disk1_file']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", CONFIG['memory']]
    # Add another disk.
    if ARGV[0] == "up" && !File.exist?(file_to_disk)
        vb.customize ['createhd', '--filename', file_to_disk, '--size', 10 * 1024]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
    end
  end

  config.omnibus.chef_version = :latest
  config.vbguest.auto_update = true

  config.vm.box = "chef/centos-7.1"
  config.vm.box_url = "chef/centos-7.1"
  config.vm.host_name = "dbfitvm"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 8085, host: 8085
  config.vm.synced_folder "..", "/var/dbfit", CONFIG['synced_folder_options']

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "dbfit_test"

    chef.json = {
      "mysql" => {
        "server_root_password" => "password",
        "server_repl_password" => "password",
        "server_debian_password" => "password",
        "bind_address" => "127.0.0.1",
      },
      "postgresql" => {
        "password" => {
          "postgres" => "postgres"
        },
        "version" => "9.4",
        "enable_pgdg_yum" => true
      },
      "java" => {
        "install_flavor" => "oracle",
        "jdk_version" => "8",
        "oracle" => {
          "accept_oracle_download_terms" => true
        }
      },
      "git" => {
        "version" => "2.4.5",
        "checksum" => "eff7fc2f8378a57aea46501ab0468052377301e264cca1f454067d3ce2fd85ca"
      },
      "run_list" => ["recipe[dbfit_test]"]
    }

    DbFit.apply_custom_config(:chef, chef)
  end

  DbFit.apply_custom_config(:vagrant, config)
end

