CREATE DATABASE NETEZZATEST
;

CREATE TABLE Users
(
  UserId	INTEGER
, Name		VARCHAR(50)
, UserName	VARCHAR(50)
)
;

CREATE OR REPLACE PROCEDURE MAKEUSER()
RETURNS INTEGER
LANGUAGE NZPLSQL AS
BEGIN_PROC
    BEGIN
       EXECUTE IMMEDIATE 'INSERT INTO Users (UserName, Name) VALUES (''user1'', ''fromproc'')';
       RETURN 1;
    END;  
END_PROC
;
