ALTER DATABASE DbFit SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE DbFit
GO

DROP LOGIN DbFit
GO

ALTER DATABASE FitNesseTestDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE FitNesseTestDB
GO

ALTER DATABASE FitNesseTestDB2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE FitNesseTestDB2
GO

DROP LOGIN FitNesseUser
GO

sp_dropmessage @msgnum = 53120
GO