# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI with Gradle
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'zulu', 'temurin' ]
        java: [ '8', '11' ]
    name: Java ${{ matrix.Java }} (${{ matrix.distribution }}) sample
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: dbfit
          POSTGRES_PASSWORD: dbfit
          POSTGRES_DB: dbfit
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Setup Oracle database
      run: docker run --name dbfitora -p 1521:1521 -v "${PWD}/test_vm/scripts/oracle/sql:/docker-entrypoint-initdb.d:ro" wnameless/oracle-xe-11g-r2 &
    - name: Wait until oracle is up
      run: for i in {1..60}; do echo "$i waiting for Oracle server startup"; docker exec dbfitora test -f /tmp/dbfit-ora-setup-done.flag && echo "[Oracle UP]" && break || sleep 6; done
    - name: Set up java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean fastbuild
    - name: Oracle integration tests
      run: ./gradlew :dbfit-java:oracle:integrationTest
